-- Analog Event Table
-- Stores labeled historical setups for Stats Service backtesting.
-- These are generated by running Chart Agent on historical data.

CREATE TABLE IF NOT EXISTS analog_event (
    analog_id BIGSERIAL PRIMARY KEY,
    symbol TEXT NOT NULL,
    event_date DATE NOT NULL,
    event_type TEXT NOT NULL,  -- PULLBACK_MA50, BREAKOUT_20D, etc.
    
    -- Context at event time (for filtering)
    sector_etf TEXT,
    vol_bucket TEXT,           -- LOW, MED, HIGH
    trend_bucket TEXT,         -- UP, DOWN, SIDEWAYS
    regime TEXT,               -- RISK_ON, RISK_OFF, HIGH_VOL, etc.
    
    -- Entry context
    entry_price NUMERIC NOT NULL,
    invalidation_price NUMERIC,
    
    -- Quality metrics
    setup_quality_score NUMERIC,
    volume_confirm BOOLEAN DEFAULT false,
    
    -- Metadata
    labeled_by TEXT DEFAULT 'chart_agent_v1',
    label_confidence NUMERIC DEFAULT 1.0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Uniqueness constraint
    UNIQUE (symbol, event_date, event_type)
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_analog_event_type ON analog_event (event_type);
CREATE INDEX IF NOT EXISTS idx_analog_event_sector ON analog_event (sector_etf);
CREATE INDEX IF NOT EXISTS idx_analog_event_regime ON analog_event (regime);
CREATE INDEX IF NOT EXISTS idx_analog_event_date ON analog_event (event_date);
CREATE INDEX IF NOT EXISTS idx_analog_event_vol ON analog_event (vol_bucket);
CREATE INDEX IF NOT EXISTS idx_analog_event_trend ON analog_event (trend_bucket);

-- Composite index for common query pattern
CREATE INDEX IF NOT EXISTS idx_analog_event_lookup 
    ON analog_event (event_type, sector_etf, vol_bucket, trend_bucket, event_date);

COMMENT ON TABLE analog_event IS 'Historical labeled setups for Stats Service backtesting';
COMMENT ON COLUMN analog_event.event_type IS 'Setup type from Chart Agent taxonomy (PULLBACK_MA50, BREAKOUT_20D, etc.)';
COMMENT ON COLUMN analog_event.vol_bucket IS 'Volatility bucket at time of setup: LOW (<1.5%), MED (1.5-3%), HIGH (>3%)';
COMMENT ON COLUMN analog_event.trend_bucket IS 'Trend at time of setup based on MA alignment';
